### ISSUE TITLE
Checkpoints for Arxiv and Pubmed 

### ISSUE THREAD

**Issue by thakursc1** [facebookresearch/bart_ls#2]
Hi , 
The paper describes it performs on par with many SOTA models for PubMed and Arxiv, why havent these model checkpoints been released ?

**Comment by xwhan** [comment]
Hi @thakursc1, we did not release some of the models for license/legal issues as some of them are not clear about the permissions. I would suggest finetuning our released pretrained checkpoint. A small number of epochs will be sufficient to achieve good performance.
